const CHALDEAN = {
  a: 1, i: 1, j: 1, q: 1, y: 1,
  b: 2, k: 2, r: 2,
  c: 3, g: 3, l: 3, s: 3,
  d: 4, m: 4, t: 4,
  e: 5, h: 5, n: 5, x: 5,
  u: 6, v: 6, w: 6,
  o: 7, z: 7,
  f: 8, p: 8
};
function reduceNumber(value) { let n = Math.abs(Number(value) || 0); while (n > 9 && ![11, 22, 33].includes(n)) n = String(n).split('').reduce((s, d) => s + Number(d), 0); return n; }
function dateParts(dob) { const [year, month, day] = String(dob).split('-').map(Number); return { year, month, day }; }
function rulingNumber(dob) { return reduceNumber(dateParts(dob).day); }
function destinyNumber(dob) { return reduceNumber(String(dob).replace(/\D/g, '').split('').reduce((s, d) => s + Number(d), 0)); }
function nameNumber(name) { const total = String(name || '').toLowerCase().replace(/[^a-z]/g, '').split('').reduce((s, ch) => s + (CHALDEAN[ch] || 0), 0); return reduceNumber(total); }
function personalYear(dob, year = new Date().getFullYear()) { const p = dateParts(dob); return reduceNumber(p.day + p.month + String(year).split('').reduce((s, d) => s + Number(d), 0)); }
function loShuGrid(dob) { const digits = String(dob).replace(/\D/g, '').split('').filter(d => d !== '0'); const counts = {}; for (let i = 1; i <= 9; i++) counts[i] = 0; digits.forEach(d => counts[d]++); return { counts, missing: Object.keys(counts).filter(k => counts[k] === 0).map(Number), repeated: Object.keys(counts).filter(k => counts[k] > 1).map(k => ({ number: Number(k), count: counts[k] })) }; }
function planeAnalysis(grid) { const c = grid.counts; return { mental: (c[4] || 0) + (c[9] || 0) + (c[2] || 0), emotional: (c[3] || 0) + (c[5] || 0) + (c[7] || 0), practical: (c[8] || 0) + (c[1] || 0) + (c[6] || 0) }; }
function calcAllNumbers(name, dob) { const grid = loShuGrid(dob); return { ruling_number: rulingNumber(dob), destiny_number: destinyNumber(dob), name_number: nameNumber(name), personal_year: personalYear(dob), lo_shu_grid: grid, plane_analysis: planeAnalysis(grid) }; }
function fallbackReport(type, name, dob, question) { const numbers = calcAllNumbers(name, dob); const reportText = `Hi ${name},\n\nYour free numerology snapshot is ready.\n\nYour Ruling Number is ${numbers.ruling_number}. This shows your natural way of reacting, deciding and handling everyday life.\n\nYour Destiny Number is ${numbers.destiny_number}. This shows the broader direction your life keeps moving towards.\n\nYour Name Number is ${numbers.name_number}. This shows how your name supports your image, work and relationships.\n\nYour Personal Year is ${numbers.personal_year}. This shows the type of phase you are currently moving through.\n\nThis free report gives the first layer only. A detailed report can go deeper into career, relationships, money, name correction, business numbers and remedies.`; return { generated: false, numbers, report_text: reportText, insights: { concerns: [question || 'General life clarity'] } }; }
async function callOpenAI(prompt) { const apiKey = process.env.OPENAI_API_KEY; if (!apiKey) return null; const model = process.env.OPENAI_MODEL || 'gpt-4.1-mini'; const response = await fetch('https://api.openai.com/v1/responses', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${apiKey}` }, body: JSON.stringify({ model, input: prompt }) }); if (!response.ok) throw new Error(`OpenAI error: ${response.status} ${await response.text()}`); const data = await response.json(); if (data.output_text) return data.output_text; return (data.output || []).flatMap(item => item.content || []).map(c => c.text || '').join('\n'); }
async function generateReport(type, name, dob, question = '') { const numbers = calcAllNumbers(name, dob); const prompt = `Write a free numerology report for Divya Bajaj.\n\nThis report is numerology only. Do not mention astrology, planets, birth time, birth place, charts, houses or nakshatra.\n\nWrite for a normal Indian user in simple Indian English. Keep it personal, clear, useful and easy to read. Do not use jargon. Do not sound like a template. Do not make fixed promises or scary claims.\n\nClient Name: ${name}\nDOB: ${dob}\nUser Focus: ${question || 'General life clarity'}\n\nNumerology Data:\n${JSON.stringify(numbers, null, 2)}\n\nUse these headings:\n1. Your Quick Snapshot\n2. What Your Birth Date Says About You\n3. Your Core Strengths\n4. Your Hidden Challenges\n5. Career and Work Direction\n6. Money and Growth Pattern\n7. Relationships and Marriage Pattern\n8. Energy and Routine Awareness\n9. Your Current Year Guidance\n10. Best Suited Professions\n11. One Simple Remedy\n12. What This Free Report Does Not Reveal\n13. Next Step With Divya\n\nMake the report 900 to 1200 words. Use short paragraphs and clear bullets. Explain Ruling Number, Destiny Number, Name Number, Personal Year, Lo Shu Grid, missing numbers, repeated numbers and mental, emotional, practical planes. The free report should feel useful, but also make the user understand that the detailed paid report can reveal deeper career, relationship, money, name correction, business number and remedy guidance. End with a graceful CTA to upgrade or book a consultation.`; try { const text = await callOpenAI(prompt); if (!text) return fallbackReport(type, name, dob, question); const concerns = []; if (question) concerns.push(question); if (numbers.lo_shu_grid.missing.length) concerns.push(`Missing numbers: ${numbers.lo_shu_grid.missing.join(', ')}`); return { generated: true, numbers, report_text: text, insights: { concerns } }; } catch (error) { console.error('[OpenAI numerology report error]', error.message); return fallbackReport(type, name, dob, question); } }
module.exports = { reduceNumber, calcAllNumbers, generateReport };