const fs=require('fs'),path=require('path'),PDF=require('pdfkit');
const A4=[595.28,841.89],P={l:45,r:45,t:132,b:688},W=A4[0]-P.l-P.r;
const C={paper:'#FCF5EB',light:'#FFF9F1',gold:'#B7873D',soft:'#D6B985',ink:'#1D1A18',muted:'#62584D',sand:'#F7ECDD',line:'#D6B985',white:'#FFFFFF'};
const LIFE=[['03','Personal Nature: Strengths And Weaknesses','personal_nature'],['04','Past Life Karma','past_life_karma'],['05','Finances','finances'],['06','Marriage And Partnership','marriage'],['07','Health And Constitution','health'],['08','Children','children'],['09','Property Purchase','property']];
const META={'How To Read This Report':'How the report works, what each layer means, and where its limits are','Your Chart And Numbers At A Glance':'The strongest chart and number signals before the detailed reading','Personal Nature: Strengths And Weaknesses':'Your natural operating style, strengths, blind spots and repeated patterns','Past Life Karma':'Symbolic karmic patterns and lessons that repeat until handled differently','Finances':'Earning patterns, financial behaviour, opportunities, leaks and timing','Marriage And Partnership':'Partnership patterns, expectations, compatibility dynamics and timing','Health And Constitution':'Constitutional tendencies, routine, stress patterns and wellbeing awareness','Children':'Children, nurturing patterns, family responsibilities and timing where supported','Property Purchase':'Home, property, stability and long-term material decisions','Remedies':'Practical first, structural second, optional observance last','Your Timing Map':'A five-year map of changing emphasis and practical direction','Closing Summary':'The five points worth carrying forward from the complete reading','Scope And Limitations':'Clear boundaries so the report remains useful and responsible'};
const clean=v=>String(v??'').replace(/\r/g,'').replace(/[\u2013\u2014]/g,'-').replace(/\s+/g,' ').trim(),arr=v=>Array.isArray(v)?v.filter(Boolean):[];
function asset(prefix){const d=path.join(process.cwd(),'public','report-v4','chunks'),n=fs.readdirSync(d).filter(x=>x.startsWith(prefix+'.')&&x.endsWith('.b64')).sort();if(!n.length)throw Error('Missing approved PDF asset '+prefix);return Buffer.from(n.map(x=>fs.readFileSync(path.join(d,x),'utf8')).join('').replace(/\s+/g,''),'base64')}
function assets(){return{cover:asset('cover'),chrome:asset('chrome'),logo:asset('logo'),portrait:asset('portrait')}}
function dob(v){const m=clean(v).match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?`${m[3]}/${m[2]}/${m[1]}`:clean(v)}
function tob(v){const m=clean(v).match(/^(\d{1,2}):(\d{2})$/);if(!m)return clean(v);let h=+m[1],ap=h>=12?'PM':'AM';h%=12;if(!h)h=12;return`${h}:${m[2]} ${ap}`}
function cover(d,l,a){d.image(a.cover,0,0,{width:A4[0],height:A4[1]});d.fillColor(C.ink).font('Times-Roman').fontSize(22).text(clean(l.name)||'Client Name',65,500,{width:260,lineBreak:false,ellipsis:true});[dob(l.dob),tob(l.tob),clean(l.pob||l.place)].forEach((v,i)=>{let y=[547.5,594.5,641.5][i],w=i===2?155:142;d.save().fillOpacity(.97).rect(104,y,w,29).fill(C.light).fillOpacity(1).fillColor(C.ink).font('Helvetica').fontSize(7.6).text(v||'-',108,y+6,{width:w-10,lineBreak:false,ellipsis:true}).strokeColor(C.soft).lineWidth(.55).moveTo(108,y+24).lineTo(104+w-8,y+24).stroke().restore()})}
function chrome(d,x,label){d.image(x.a.chrome,0,0,{width:A4[0],height:A4[1]});d.image(x.a.logo,247,16.16,{width:101,height:80.68});d.fillColor(C.ink).font('Helvetica').fontSize(6.4).text(clean(label||'The Integrated Life Report').toUpperCase(),442,89.4,{width:108,align:'right',lineBreak:false,ellipsis:true});d.x=P.l;d.y=P.t}
function footer(d,x,i){d.save().image(x.a.portrait,472,714.05,{width:123,height:126.9}).fillColor(C.gold).font('Helvetica-Bold').fontSize(7.1).text(String(i+1).padStart(2,'0'),438,798,{width:22,align:'right',lineBreak:false}).restore()}
function rem(x){return P.b-x.d.y}function page(x,label){x.label=label||x.label;x.kind='content';x.d.addPage({size:A4,margins:{top:P.t,bottom:A4[1]-P.b,left:P.l,right:P.r}});let q=x.d.bufferedPageRange();return q.start+q.count-1}function space(x,n){if(rem(x)<n)page(x,x.label)}
function measure(d,s,w=W,o={}){d.font(o.font||'Helvetica').fontSize(o.size||8.8);return d.heightOfString(clean(s),{width:w,lineGap:o.gap??3})}
function para(x,s,o={}){s=clean(s);if(!s)return;let w=o.width||W,h=measure(x.d,s,w,o);if(h<=108)space(x,h+7);x.d.fillColor(o.color||C.ink).font(o.font||'Helvetica').fontSize(o.size||8.8).text(s,o.x||P.l,x.d.y,{width:w,lineGap:o.gap??3});x.d.y+=o.after??11}
function sub(x,s){space(x,58);x.d.fillColor(C.ink).font('Helvetica-Bold').fontSize(10).text(clean(s),P.l,x.d.y,{width:W});x.d.y+=7}
function section(x,n,t){x.label=t;if(rem(x)<105)page(x,t);else if(x.d.y>P.t+4)x.d.y+=22;let q=x.d.bufferedPageRange();x.pages[t]=q.start+q.count;x.d.fillColor(C.gold).font('Helvetica-Bold').fontSize(7.4).text(n,P.l,x.d.y,{characterSpacing:1.05});x.d.y+=18;x.d.fillColor(C.ink).font('Times-Bold').fontSize(22).text(t,P.l,x.d.y,{width:W});x.d.y+=5;if(META[t]){x.d.fillColor(C.muted).font('Times-Italic').fontSize(9.2).text(META[t],P.l,x.d.y,{width:W,lineGap:1.5});x.d.y+=12}x.d.strokeColor(C.soft).lineWidth(.5).moveTo(P.l,x.d.y).lineTo(A4[0]-P.r,x.d.y).stroke();x.d.y+=16}
function bullets(x,a){arr(a).forEach(v=>{v=clean(typeof v==='string'?v:JSON.stringify(v));if(!v)return;let w=W-17,h=measure(x.d,v,w);if(h<=105)space(x,h+12);let y=x.d.y;x.d.fillColor(C.gold).circle(P.l+3,y+5,1.7).fill().fillColor(C.ink).font('Helvetica').fontSize(8.8).text(v,P.l+15,y,{width:w,lineGap:3});x.d.y=y+h+7})}
function callout(x,label,s,o={}){s=clean(s);if(!s)return;let iw=W-34,bh=measure(x.d,s,iw,{font:o.font||'Helvetica',size:o.size||9})+45;space(x,bh+11);let y=x.d.y;x.d.roundedRect(P.l,y,W,bh,5).fillAndStroke(o.fill||C.sand,C.line).rect(P.l,y,4,bh).fill(C.gold).fillColor(C.gold).font('Helvetica-Bold').fontSize(6.6).text(clean(label).toUpperCase(),P.l+17,y+11,{width:iw,characterSpacing:.65}).fillColor(C.ink).font(o.font||'Helvetica').fontSize(o.size||9).text(s,P.l+17,y+27,{width:iw,lineGap:3});x.d.y=y+bh+11}
function conf(x,s){s=clean(s);if(!s)return;let bw=W-122,h=Math.max(42,measure(x.d,s,bw,{size:8.1,gap:2.5})+18);space(x,h+11);let y=x.d.y;x.d.roundedRect(P.l,y,W,h,4).fillAndStroke('#F0DFC6',C.line).fillColor(C.gold).font('Helvetica-Bold').fontSize(6.6).text('CONFIDENCE',P.l+14,y+13,{characterSpacing:.65}).fillColor(C.ink).font('Helvetica').fontSize(8.1).text(s,P.l+102,y+10,{width:bw,lineGap:2.5});x.d.y=y+h+11}
function table(x,cols,rows,o={}){let size=o.size||7.2,hh=o.hh||26;function head(){space(x,hh+20);let y=x.d.y,xx=P.l;cols.forEach(c=>{x.d.rect(xx,y,c.w,hh).fillAndStroke(C.gold,C.gold).fillColor(C.white).font('Helvetica-Bold').fontSize(6.6).text(c.label,xx+6,y+8,{width:c.w-12,align:c.align||'left'});xx+=c.w});x.d.y=y+hh}head();arr(rows).forEach((r,idx)=>{let vals=cols.map(c=>clean(r[c.key])),hs=vals.map((v,i)=>measure(x.d,v,cols[i].w-12,{size,gap:o.gap??2})),rh=Math.max(o.min||31,...hs.map(v=>v+14));if(rem(x)<rh){page(x,x.label);head()}let y=x.d.y,xx=P.l;cols.forEach((c,i)=>{x.d.rect(xx,y,c.w,rh).fillAndStroke(idx%2?C.sand:C.light,C.line).fillColor(C.ink).font('Helvetica').fontSize(size).text(vals[i],xx+6,y+7,{width:c.w-12,lineGap:o.gap??2,align:c.align||'left'});xx+=c.w});x.d.y=y+rh});x.d.y+=16}
function placeholder(x){x.toc=page(x,'Table of Contents')}
function summary(x,l,r){x.summary=page(x,'Your Report In One Page');let first=clean(l.name).split(' ')[0]||'Your';x.d.fillColor(C.gold).font('Helvetica-Bold').fontSize(7.4).text('YOUR REPORT IN ONE PAGE',P.l,x.d.y,{characterSpacing:1.05});x.d.y+=20;x.d.fillColor(C.ink).font('Times-Bold').fontSize(22).text(`The big picture, ${first}`,P.l,x.d.y,{width:W});x.d.y+=12;callout(x,'The strongest signal',r.glance?.headline_finding||'The strongest themes in the report are shown below.',{font:'Times-Bold',size:9.4});sub(x,'Seven-area pulse');table(x,[{label:'AREA',key:'area',w:91},{label:'WHAT TO NOTICE',key:'insight',w:W-91}],LIFE.map(([,t,k])=>{let a=r.life_areas?.[k]||{},z=clean(a.convergence||a.tension_or_silence||a.intro),m=z.match(/^(.{1,260}?[.!?])(?:\s|$)/),s=m?m[1]:z;return{area:t.replace(': Strengths And Weaknesses','').replace(' And Constitution','').replace(' And Partnership','').replace(' Purchase',''),insight:s.length>170?s.slice(0,167)+'...':s}}),{size:7.15,min:27,hh:24,gap:1.8});let tm=arr(r.timing_map)[0];if(tm)callout(x,'Your current chapter',`${clean(tm.period)}: ${clean(tm.combined_reading||tm.astrology||tm.numerology)}`,{fill:C.light,size:8.3});para(x,l.question?`Your main concern is "${clean(l.question)}". The pages that follow show where the report is confident, where the picture is mixed, and what is actually useful to do next.`:'The pages that follow show where the report is confident, where the picture is mixed, and what is actually useful to do next.',{font:'Times-Italic',size:9.2,after:0})}
function primer(x,r){section(x,'01','How To Read This Report');let p=r.primer||{};para(x,p.purpose,{font:'Times-Roman',size:11.2,after:16});sub(x,'The two systems used in your report');para(x,p.systems);sub(x,'The four ideas you need');let f=p.four_ideas||{};[['01','Houses are life departments',f.houses],['02','Planets are the officers in charge',f.planets],['03','Dasha is whose turn it is',f.dasha],['04','The chain of command',f.chain_of_command]].forEach(([n,t,b])=>{space(x,62);let y=x.d.y;x.d.fillColor(C.gold).font('Times-Bold').fontSize(18).text(n,P.l,y,{width:32}).fillColor(C.ink).font('Helvetica-Bold').fontSize(10).text(t,P.l+42,y+2,{width:W-42});x.d.y=y+21;para(x,b,{x:P.l+42,width:W-42,size:8.8})});callout(x,'Convergence method',p.convergence_method);sub(x,'What this report will not do');bullets(x,p.limits);para(x,p.disclaimer,{font:'Times-Italic',size:8.7})}
function glance(x,r){section(x,'02','Your Chart And Numbers At A Glance');let g=r.glance||{};callout(x,'Headline finding',g.headline_finding,{font:'Times-Bold',size:9.4});sub(x,'The astrological layer');table(x,[{label:'ELEMENT',key:'element',w:92},{label:'YOUR POSITION',key:'position',w:142},{label:'WHAT IT MEANS',key:'plain_meaning',w:W-234}],g.astrology,{size:7.2,min:34});sub(x,'The numerological layer');table(x,[{label:'NUMBER',key:'label',w:104},{label:'VALUE',key:'value',w:42,align:'center'},{label:'DERIVED FROM',key:'derived_from',w:133},{label:'PLAIN MEANING',key:'plain_meaning',w:W-279}],g.numerology,{size:7.05,min:31})}
function life(x,n,t,a={}){section(x,n,t);para(x,a.intro,{font:'Times-Roman',size:11,after:16});sub(x,'What your birth chart shows');para(x,a.birth_chart);sub(x,'What your numbers show');para(x,a.numbers);callout(x,'Where the two systems agree',a.convergence,{font:'Times-Bold',size:9.2});sub(x,'Where the picture is mixed');para(x,a.tension_or_silence);sub(x,'Timing');arr(a.timing).length?bullets(x,a.timing):para(x,'No timing claim is made because the verified data does not support one.');sub(x,'What to actually do about it');bullets(x,a.actions);conf(x,a.confidence)}
function remedies(x,r){section(x,'10','Remedies');let z=r.remedies||{};para(x,z.intro,{font:'Times-Roman',size:11,after:16});sub(x,'Priority one: behavioural practices');arr(z.behavioural).forEach((v,i)=>callout(x,`Practice ${String(i+1).padStart(2,'0')}`,[v.pattern&&`Pattern: ${v.pattern}`,v.practice&&`Practice: ${v.practice}`,v.rhythm&&`Rhythm: ${v.rhythm}`,v.purpose&&`Purpose: ${v.purpose}`].filter(Boolean).join('  '),{fill:C.light,size:8.4}));sub(x,'Priority two: professional and structural');bullets(x,z.professional_structural);sub(x,'Priority three: optional traditional observance');arr(z.traditional_observance).forEach(v=>callout(x,v.planet||'Optional observance',[v.why,v.observance].filter(Boolean).join('  '),{size:8.4}));callout(x,'Gemstones',z.gemstone_note||'No gemstone is recommended in this report without a separate dedicated planetary-strength assessment.',{fill:C.light,size:8.5})}
function timing(x,r){section(x,'11','Your Timing Map');table(x,[{label:'PERIOD',key:'period',w:66},{label:'ASTROLOGY',key:'astrology',w:104},{label:'NUMEROLOGY',key:'numerology',w:93},{label:'COMBINED READING',key:'combined_reading',w:W-309},{label:'CONF.',key:'confidence',w:46}],r.timing_map,{size:6.7,min:42,gap:1.8});if(r.major_shift?.period&&r.major_shift?.reading)callout(x,`Major shift: ${r.major_shift.period}`,`${r.major_shift.reading} ${r.major_shift.confidence||''}`,{size:8.4})}
function closing(x,r){section(x,'12','Closing Summary');arr(r.closing_summary).forEach((v,i)=>{space(x,54);let y=x.d.y,w=W-48,h=measure(x.d,v,w,{size:9.1});x.d.fillColor(C.gold).font('Times-Bold').fontSize(20).text(String(i+1).padStart(2,'0'),P.l,y,{width:36}).fillColor(C.ink).font('Helvetica').fontSize(9.1).text(clean(v),P.l+48,y+1,{width:w,lineGap:3});x.d.y=y+Math.max(43,h+10);x.d.strokeColor(C.line).lineWidth(.4).moveTo(P.l+48,x.d.y).lineTo(A4[0]-P.r,x.d.y).stroke();x.d.y+=11})}
function toc(x){x.d.switchToPage(x.toc);chrome(x.d,x,'Table of Contents');x.d.fillColor(C.gold).font('Helvetica-Bold').fontSize(7.4).text('TABLE OF CONTENTS',P.l,x.d.y,{characterSpacing:1.05});x.d.y+=20;x.d.fillColor(C.ink).font('Times-Bold').fontSize(22).text('Inside your Integrated Life Report',P.l,x.d.y,{width:W});x.d.y+=18;let e=[['00','Your Report In One Page',x.summary+1],['01','How To Read This Report',x.pages['How To Read This Report']],['02','Your Chart And Numbers At A Glance',x.pages['Your Chart And Numbers At A Glance']],...LIFE.map(([n,t])=>[n,t,x.pages[t]]),['10','Remedies',x.pages.Remedies],['11','Your Timing Map',x.pages['Your Timing Map']],['12','Closing Summary',x.pages['Closing Summary']],['13','Scope And Limitations',x.pages['Scope And Limitations']]];e.forEach(([n,t,p])=>{let y=x.d.y;x.d.fillColor(C.gold).font('Helvetica-Bold').fontSize(7.1).text(n,P.l,y+2,{width:25}).fillColor(C.ink).font('Helvetica').fontSize(8.7).text(t,P.l+34,y,{width:W-84}).strokeColor(C.soft).lineWidth(.35).dash(1,{space:2}).moveTo(P.l+260,y+10).lineTo(A4[0]-P.r-30,y+10).stroke().undash().fillColor(C.gold).font('Helvetica-Bold').fontSize(7.8).text(String(p||''),A4[0]-P.r-30,y,{width:30,align:'right'});x.d.y=y+28})}
async function generateApprovedPaidPdfV4({lead={},reportJson=null}){if(!reportJson||typeof reportJson!=='object')throw Error('Approved V4 PDF requires structured report JSON');let a=assets();return new Promise((resolve,reject)=>{try{let d=new PDF({autoFirstPage:false,bufferPages:true,info:{Title:'Divya Bajaj - The Integrated Life Report',Author:'Divya Bajaj',Subject:'Nadi Astrology + Vedic Numerology'}}),chunks=[],x={d,a,kind:'cover',label:'The Integrated Life Report',toc:null,summary:null,pages:{}};d.on('data',c=>chunks.push(c));d.on('end',()=>resolve(Buffer.concat(chunks)));d.on('error',reject);d.on('pageAdded',()=>{if(x.kind==='content')chrome(d,x,x.label)});d.addPage({size:A4,margins:{top:0,bottom:0,left:0,right:0}});cover(d,lead,a);placeholder(x);summary(x,lead,reportJson);primer(x,reportJson);glance(x,reportJson);LIFE.forEach(([n,t,k])=>life(x,n,t,reportJson.life_areas?.[k]||{}));remedies(x,reportJson);timing(x,reportJson);closing(x,reportJson);section(x,'13','Scope And Limitations');bullets(x,reportJson.scope_limitations);toc(x);let q=d.bufferedPageRange();for(let i=q.start+1;i<q.start+q.count;i++){d.switchToPage(i);footer(d,x,i)}d.end()}catch(e){reject(e)}})}
module.exports={generateApprovedPaidPdfV4};
